### ISSUE TITLE
AttributeError: 'FastApiAppPacker' object has no attribute 'info'

### ISSUE THREAD

**Issue by DhanshreeA** [ersilia-os/ersilia-pack#2]
Logs:
```
#11 0.522 Copying metadata
#11 0.522 Copying model
#11 0.522 Copying the favicon
#11 0.522 File downloaded and saved to /root/eos/repository/eos80ch/20240610-98b94537-2249-4eb5-bf89-fb06ebb347a0/static/favicon.ico
#11 0.522 Traceback (most recent call last):
#11 0.522   File "/usr/local/bin/ersilia_model_pack", line 33, in <module>
#11 0.522     sys.exit(load_entry_point('ersilia-pack', 'console_scripts', 'ersilia_model_pack')())
#11 0.522   File "/root/ersilia-pack/src/packer.py", line 195, in main
#11 0.522     fp.pack()
#11 0.522   File "/root/ersilia-pack/src/packer.py", line 176, in pack
#11 0.523     self._get_input_schema()
#11 0.523   File "/root/ersilia-pack/src/packer.py", line 80, in _get_input_schema
#11 0.523     print(self.info)
#11 0.523 AttributeError: 'FastApiAppPacker' object has no attribute 'info'
```

It seems the culprit is that in [`FastApiAppPacker.pack`](https://github.com/ersilia-os/ersilia-pack/blob/ca742630ce03bbe569ba5f0f6289130456f71d26/src/packer.py#L171), the method `_get_input_schema` is called before `_get_info`, however the `info` attribute is only set within `_get_info`.

**Comment by DhanshreeA** [comment]
I see that within the commit: https://github.com/ersilia-os/ersilia-pack/commit/ca742630ce03bbe569ba5f0f6289130456f71d26 `_get_info_from_metadata` was renamed to `_get_info`, and within `FastApiAppPacker.pack` it was called before `_get_input_schema`. I think the line that sets value for a `card` key was also accidentally [deleted](https://github.com/ersilia-os/ersilia-pack/commit/ca742630ce03bbe569ba5f0f6289130456f71d26#diff-ea5adf0cf1cdb141f46861cca7ba7f7b6ad8661d8ef7e14d9b2bd8a7451e962cL69) (unless it is desired?)

I'm fixing these issues in a PR.
